-d D:\OpenFPGAPrjs\02_1_uart_diy\gowin_prj\fpga_project\impl\gwsynthesis\fpga_project.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst D:\OpenFPGAPrjs\02_1_uart_diy\gowin_prj\fpga_project\src\tangnano9k.cst
-cfg D:\OpenFPGAPrjs\02_1_uart_diy\gowin_prj\fpga_project\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
